### ISSUE TITLE
Contains on Collection<T> field throws InvalidOperationException 

### ISSUE THREAD

**Issue by mojobec** [Chorus/LINQtoCRM#1]
getting the error when trying to filter a multiselect pickList
 ` provider.Linq<contact>().Where(c => c.gendercode.Contains(new Picklist(1)))`

`c.gendercode` is a `PicklistCollection` that is a simple `Collection<Picklist>`

**Comment by mojobec** [comment]
@aronmek looks like you touched that code recently

**Comment by aronmek** [comment]
@mojobec It should work now.
